### ISSUE TITLE
NotADirectoryError: 在重打包的时候出现的文件夹小问题

### ISSUE THREAD

**Issue by sonderlau** [Mas0nShi/typoraCracker#13]
## 环境

- WSL 2  Ubuntu 20.04.3
- Python 3.8.10
- 已拉取最新版仓库代码 2021-12-04 10:04

## 复现

```bash
python typora.py -u /mnt/d/repositories/typoraCracker/out/dec_app ./outfiles
```

```
2021-12-04 10:15:59.219 | ERROR    | __main__:packWenc:103 - plz input Directory for app.asar
Traceback (most recent call last):
  File "typora.py", line 151, in <module>
    main()
  File "typora.py", line 146, in main
    args.mode(args.asarPath, args.dirPath, args.format)
  File "typora.py", line 104, in packWenc
    raise NotADirectoryError
NotADirectoryError
```

错误原因: 未新建 `outfiles` 文件夹， 手动创建后即解决。

## 改进

对生成文件的地址文件夹 `args.dirPath` 检测若不存在即进行新建

**Comment by Mas0nShi** [comment]
收到，近期更新。

**Comment by Mas0nShi** [comment]
已修复。
