### ISSUE TITLE
python 3.10执行报错，typora的版本是1.1.15

### ISSUE THREAD

**Issue by zdhsoft** [Mas0nShi/typoraCracker#32]
python typora.py -u ./dec_app/ .
Traceback (most recent call last):
  File "D:\temp\m\typoraCracker\typora.py", line 167, in <module>
    main()
  File "D:\temp\m\typoraCracker\typora.py", line 162, in main
    args.mode(args.asarPath, args.dirPath, args.format)
  File "D:\temp\m\typoraCracker\typora.py", line 116, in packWenc
    _newDir(outPath)
  File "D:\temp\m\typoraCracker\typora.py", line 36, in _newDir
    rmtree(_path)
  File "C:\Users\rex\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 739, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\rex\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\rex\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\rex\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\rex\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 617, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\rex\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 615, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] 拒绝访问。: '.\\.git\\objects\\pack\\pack-1f8192f2b6b8d0d7d1fd65a
7ac63a8b412c0ddd8.idx'

**Comment by Mas0nShi** [comment]
请尝试更换解包保存路径

![image](https://user-images.githubusercontent.com/60805843/155085407-09d02d88-86ba-4279-b8c7-3909167650d6.png)
