### ISSUE TITLE
1.2.2-dev 解密失败

### ISSUE THREAD

**Issue by Delppine1024** [Mas0nShi/typoraCracker#36]
我在给 1.2.2-dev 做解密时，遇到这样的错误：
2022-03-14 20:21:43.385 | INFO     | __main__:extractWdec:72 - extract asar file: D:\Program Files (x86_User)/Typora/resources/app.asar
2022-03-14 20:21:43.415 | SUCCESS  | __main__:extractWdec:75 - extract ended.
2022-03-14 20:21:43.417 | INFO     | __main__:extractWdec:77 - read Directory: ./workstation/outfile_1.2.2-dev/typoraCrackerTemp
2022-03-14 20:21:43.418 | INFO     | __main__:extractWdec:85 - set Directory: ./workstation/outfile_1.2.2-dev\dec_app
2022-03-14 20:21:43.428 | INFO     | __main__:extractWdec:92 - open file: atom.js
Traceback (most recent call last):
  File "typora.py", line 182, in <module>
    main()
  File "typora.py", line 177, in main
    args.mode(args.asarPath, args.dirPath, args.format)
  File "typora.py", line 95, in extractWdec
    scode = decScript(scode, prettify)
  File "typora.py", line 52, in decScript
    code = unpad(ins.decrypt(cipherText), 16, 'pkcs7')
  File "C:\ProgramData\Anaconda3\envs\typora_cracker\lib\site-packages\Crypto\Util\Padding.py", line 92, in unpad
    raise ValueError("Padding is incorrect.")
ValueError: Padding is incorrect.

OS: Windows 10 Pro, 21H2
Python: 3.8.12

现象：atom.js 无法解密

**Comment by Mas0nShi** [comment]
已复现，此版本更改了key，暂时将此版本使用脚本更新至分支：
https://github.com/Mas0nShi/typoraCracker/tree/1.2.2-dev

**Comment by Delppine1024** [comment]
新的分支确实可以解包了，但是反向compress后替换掉原先的app.asar，会导致错误，error提示为乱码
![image](https://user-images.githubusercontent.com/100767917/158214997-b5bfa2e6-2a92-426f-a9b5-7a9fe5b070c1.png)

**Comment by Mas0nShi** [comment]
此版本已将iv固定
