### ISSUE TITLE
大佬，解压出现Padding is incorrect错误

### ISSUE THREAD

**Issue by lsq** [Mas0nShi/typoraCracker#40]
# python typora.py ~/app.asar ./
2022-03-24 15:56:09.515 | INFO     | __main__:extractWdec:72 - extract asar file: C:/msys64/home/Administrator/app.asar
Couldn't copy file ./main.node, no extracted directory
2022-03-24 15:56:09.517 | SUCCESS  | __main__:extractWdec:75 - extract ended.
2022-03-24 15:56:09.518 | INFO     | __main__:extractWdec:77 - read Directory: ./typoraCrackerTemp
2022-03-24 15:56:09.519 | INFO     | __main__:extractWdec:85 - set Directory: ./dec_app
2022-03-24 15:56:09.519 | INFO     | __main__:extractWdec:92 - open file: atom.js
Traceback (most recent call last):
  File "C:\Users\Administrator\github\typoraCracker\typora.py", line 182, in <module>
    main()
  File "C:\Users\Administrator\github\typoraCracker\typora.py", line 177, in main
    args.mode(args.asarPath, args.dirPath, args.format)
  File "C:\Users\Administrator\github\typoraCracker\typora.py", line 95, in extractWdec
    scode = decScript(scode, prettify)
  File "C:\Users\Administrator\github\typoraCracker\typora.py", line 52, in decScript
    code = unpad(ins.decrypt(cipherText), 16, 'pkcs7')
  File "C:/msys64/mingw64/lib/python3.9/site-packages/Crypto/Util/Padding.py", line 92, in unpad
    raise ValueError("Padding is incorrect.")
ValueError: Padding is incorrect.

**Comment by Mas0nShi** [comment]
请提供typora版本

**Comment by Delppine1024** [comment]
我觉得可能是你的分支用得不对

**Comment by justcyl** [comment]
> 请提供typora版本

同出现该问题，typora版本1.2，python版本3.9.7

**Comment by sti1l-0** [comment]
typora@1.2.3
python@3.9.11
反馈同上

**Comment by Mas0nShi** [comment]
https://github.com/Mas0nShi/typoraCracker/releases

**Comment by Mas0nShi** [comment]
#38 相似问题

**Comment by Delppine1024** [comment]
在linux端遇到同样的问题，typora 1.2.3

**Comment by Delppine1024** [comment]
在linux x64 1.2.3 也出现了同样的问题，padding incorrect

**Comment by lsq** [comment]
typora@1.2.3
python@3.9.11

**Comment by Mas0nShi** [comment]
请使用对应release版本

**Comment by Mas0nShi** [comment]
已添加1.2.3-x64-linux

**Comment by lsq** [comment]
我试下最新release版本一样报padding incorrect错误

**Comment by Mas0nShi** [comment]
> 我试下最新release版本一样报padding incorrect错误

请提供os arch

**Comment by Delppine1024** [comment]
最新已经迭代到了 1.2.4，建议可以自己找一下 key 和 iv

**Comment by justleap** [comment]
> 最新已经迭代到了 1.2.4，建议可以自己找一下 key 和 iv

出现了解压失败，大佬，请问一下怎么看typora的key和iv

**Comment by SnapdragonLee** [comment]
> > 最新已经迭代到了 1.2.4，建议可以自己找一下 key 和 iv
> 
> 
> 
> 1.2.4出现了解压失败，大佬，请问一下怎么看typora的key和iv

建议看一下最新的issue
