### ISSUE TITLE
执行 typora.py 报错 

### ISSUE THREAD

**Issue by leess447987343** [Mas0nShi/typoraCracker#43]
python版本: 3.10.4
Typora版本: 1.2.3
```
Traceback (most recent call last):
  File "D:\Program Files\typoraCracker\typora.py", line 182, in <module>
    main()
  File "D:\Program Files\typoraCracker\typora.py", line 177, in main
    args.mode(args.asarPath, args.dirPath, args.format)
  File "D:\Program Files\typoraCracker\typora.py", line 95, in extractWdec
    scode = decScript(scode, prettify)
  File "D:\Program Files\typoraCracker\typora.py", line 52, in decScript
    code = unpad(ins.decrypt(cipherText), 16, 'pkcs7')
  File "C:\Users\PO\AppData\Local\Programs\Python\Python310\lib\site-packages\Crypto\Util\Padding.py", line 92, in unpad
    raise ValueError("Padding is incorrect.")
ValueError: Padding is incorrect.
```
![image](https://user-images.githubusercontent.com/42337141/160228380-2c87f1e7-5345-4c0b-b7ba-8647d1e592b7.png)

**Comment by leess447987343** [comment]
版本使用错误，抱歉
