### ISSUE TITLE
python typora.py执行报错

### ISSUE THREAD

**Issue by remainfox** [Mas0nShi/typoraCracker#44]
`System Version`: Win10 
`Python Version`: Python3.69
`Typora Version`: 1.2.3

python typora.py执行报错，错误如下

```shell
> python typora.py D:\programs\Typora\resources\app.asar workstation\outfile\
2022-03-26 22:53:44.567 | INFO     | __main__:extractWdec:72 - extract asar file: D:\programs\Typora\resources\app.asar
2022-03-26 22:53:44.574 | SUCCESS  | __main__:extractWdec:75 - extract ended.
2022-03-26 22:53:44.575 | INFO     | __main__:extractWdec:77 - read Directory: workstation\outfile\typoraCrackerTemp
2022-03-26 22:53:44.576 | INFO     | __main__:extractWdec:85 - set Directory: workstation\outfile\dec_app
2022-03-26 22:53:44.578 | INFO     | __main__:extractWdec:92 - open file: atom.js
Traceback (most recent call last):
  File "typora.py", line 182, in <module>
    main()
  File "typora.py", line 177, in main
    args.mode(args.asarPath, args.dirPath, args.format)
  File "typora.py", line 95, in extractWdec
    scode = decScript(scode, prettify)
  File "typora.py", line 52, in decScript
    code = unpad(ins.decrypt(cipherText), 16, 'pkcs7')
  File "D:\01-work\01-DevelopEnv\Python3\lib\site-packages\Crypto\Util\Padding.py", line 92, in unpad
    raise ValueError("Padding is incorrect.")
ValueError: Padding is incorrect.

```

```
> python --version
Python 3.6.8rc1
```

**Comment by remainfox** [comment]
**最后生成了激活码也是无法激活的**

![image](https://user-images.githubusercontent.com/10653136/160246003-bc472c7f-e958-4bef-aee3-9a1a6a4bb30e.png)

![image](https://user-images.githubusercontent.com/10653136/160245967-acb14768-7fe5-4cef-a6bb-a74a3de29078.png)

**Comment by Mas0nShi** [comment]
关于解包错误 #38 
关于破解，无效issue
