### ISSUE TITLE
执行报错

### ISSUE THREAD

**Issue by BaoPiao** [Mas0nShi/typoraCracker#64]
python版本：
Python 3.10.4

运行系统：
windows 10

执行命令：
python typora.py D:\soft\Typora\resources\app.asar   D:\soft\typoraCracker\wrokstation\outfile

报错如下：
2022-04-11 20:27:09.298 | INFO     | __main__:extractWdec:96 - open file: atom.js
Traceback (most recent call last):
  File "D:\soft\typoraCracker\typora.py", line 186, in <module>
    main()
  File "D:\soft\typoraCracker\typora.py", line 181, in main
    args.mode(args.asarPath, args.dirPath, args.format)
  File "D:\soft\typoraCracker\typora.py", line 99, in extractWdec
    scode = decScript(scode, prettify)
  File "D:\soft\typoraCracker\typora.py", line 53, in decScript
    code = unpad(ins.decrypt(cipherText), 16, 'pkcs7')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\Crypto\Util\Padding.py", line 92, in unpad
    raise ValueError("Padding is incorrect.")
ValueError: Padding is incorrect.

**Comment by BaoPiao** [comment]
使用typora为老版本，所以导致无法使用！
